require("plugins")
require("key-mappings")
require("options")
require("gui-config")
require("gui-options")
require("lualine-config")
require("telescope")
require("autocompletions")
require("chatgpt-config")
--lsp autocomplete:
require("lsp.mason")
require("lsp.lspconfig")
require("lsp.lspsaga")
-- require("lsp.null-ls")
require("gitsigns")
